name: Firestore Daily Update

on:
  schedule:
    - cron: "01 19 * * *"
  workflow_dispatch:

jobs:
  update-firestore:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Install dependencies
      run: npm install firebase-admin

    # - name: Write Firebase credentials to file
    #   run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase_credentials.json

    - name: Run Firestore Update Script
      run: node scripts/dailyChallenge.js

    # - name: Clean up credentials file
    #   run: rm -f firebase_credentials.json
